[root@ip-172-31-33-209 tomcat]# more /tmp/tomcat.yml
---
- name: tomcat installation
  hosts: localhost
  become: yes
  tasks:
  - name: tomcat install
    yum:
     name:
      - tomcat
      - tomcat-admin-webapps*
      - tomcat-docs-webapp*
      - tomcat-jsvc*
      - tomcat-webapps*
     state: present
#  - service: name=tomcat state=started enabled=yes
  - name: editing the file
    lineinfile:
     path: /etc/tomcat/tomcat-users.xml
     regexp: "{{item.regex}}"
     line: "{{item.line}}"
    with_items:
     - {regex: '^<user name="admin"', line: '<user name="admin" password="admin321" roles="admin,manager,admin-gui,admin-script,manager-gui,mana
ger-script,manager-jmx,manager-status" />'}
     - {regex: '<!-- <role rolename="manager-status"/> -->', line: '<role rolename="manager-status"/>'}
    notify:
        - restart tomcat

  - name: deploying war file for tomcat
    copy: src=/var/lib/jenkins/workspace/maven-webapp/target dest=/var/lib/tomcat/webapps/

  handlers:
    - name: restart tomcat
      service: name=tomcat state=restarted enabled=yes
